groups:
  - name: all
    jobs:
    - terraform-plan
    - terraform-apply
    - terraform-destroy

resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: '0.11.14'

resources:
  - name: git_stack
    type: git
    check_every: 2m
    source:
      uri: ((terraform_repo))
      branch: master
      private_key: ((git_ssh_key))
  - name: tfstate
    type: terraform
    source:
      env_name: dev
      backend_type: s3
      backend_config:
        bucket: ((terraform_storage_bucket_name))
        key: eks/terraform.tfstate
        region: ((aws_default_region))
        access_key: ((aws_access_key))
        secret_key: ((aws_secret_key))
      vars:
        access_key: ((aws_access_key))
        secret_key: ((aws_secret_key))
        aws_region: ((aws_default_region))

jobs:
  - name: terraform-plan
    plan:
    - do:
      - get: git_stack
      - put: tfstate
        params:
          env_name: dev
          plan_only: true
          terraform_source: git_stack/eks-stack-tf01114

  - name: terraform-apply
    plan:
    - do:
      - get: git_stack
      - put: tfstate
        params:
          env_name: dev
          plan_run: true
          terraform_source: git_stack/eks-stack-tf01114
  - name: terraform-destroy
    plan:
    - do:
      - get: git_stack      
      - put: tfstate
        params:
          env_name: dev
          action: destroy
          terraform_source: git_stack/eks-stack-tf01114
        get_params:
          action: destroy
