groups:
  - name: all
    jobs:
    - lambda-build
    - unittest
    - terraform-plan

resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: '0.11.13'

resources:
  - name: git_lambda-code
    type: git
    check_every: 2m
    source:
      uri: ((lambda_git_repository))
      branch: ((lambda_git_branch))
      private_key: ((lambda_git_ssh_key))

  - name: git_stack
    type: git
    check_every: 2m
    source:
      uri: ((lambda_git_repository))
      branch: stacks
      private_key: ((lambda_git_ssh_key))
      paths:
        - stack-lambda/terraform/*

  - name: s3_lambda-release
    type: s3
    source:
      bucket: ((lambda_release_bucket_name))
      versioned_file: ((lambda_release_bucket_object_path))
      private: true
      region_name: ((aws_default_region))
      access_key_id: ((aws_access_key))
      secret_access_key: ((aws_secret_key))

  - name: tfstate
    type: terraform
    source:
      env_name: ((env))
      backend_type: s3
      backend_config:
        bucket: ((terraform_storage_bucket_name))
        key: ((terraform_storage_bucket_path))/terraform.tfstate
        region: ((aws_default_region))
        access_key: ((aws_access_key))
        secret_key: ((aws_secret_key))
      vars:
        access_key: ((aws_access_key))
        secret_key: ((aws_secret_key))
        aws_region: ((aws_default_region))
        env: ((env))
        project: ((project))
        customer: ((customer))

jobs:
  - name: lambda-build
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - do:
      - get: git_lambda-code
        trigger: true

      - task: build-release
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /bin/bash
            args:
            - -exc
            - |
              DIR=${PWD}
              cd ${DIR}/code/
              zip -r ${DIR}/release/((project)).zip *
          inputs:
          - name: git_lambda-code
            path: code
          outputs:
          - name: release
            path: "release"

      - put: s3_lambda-release
        params:
          acl: private
          file: release/((project)).zip

  - name: unittest
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - do:
      - get: git_lambda-code
        passed: [lambda-build]
      - get: s3_lambda-release
        trigger: true
        passed: [lambda-build]

      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /bin/bash
            args:
            - -exc
            - |
              unzip code/((project)).zip
          inputs:
          - name: s3_lambda-release
            path: code

  - name: terraform-plan
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - do:
      - get: git_lambda-code
        passed: [unittest]
      - get: git_stack
        trigger: true
      - put: tfstate
        params:
          env_name: ((env))
          plan_only: true
          terraform_source: git_stack/stack-lambda/terraform
