name: test2
canonical: 149-test2
author: suresh kumar
description: test2
type: stack
image: ""
keywords:
- test2
technologies: []
config:
  pipeline:
    pipeline:
      path: pipeline/terraform-pipeline.yaml
    variables:
      path: pipeline/variables.sample.yaml
  terraform:
    149-test2:
      destination: ($ project $)/terraform/($ environment $)/149-test2.tf
      path: terraform/149-test2.tf.sample
